services:
  web:
    build: .
    image: django-cwm:latest
    container_name: django_cwm
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"